### ISSUE TITLE
1666+ new word

### ISSUE THREAD

**Issue by HazemKhaled** [Magento2Translations/language_tr_tr#1]
Hi @MrGekko ,

Official package has 1730 translated line, while ours has only 49, please update the csv file

**Comment by HazemKhaled** [comment]
You can share how you export only translated lines in csv maybe i can help with pl

**Comment by MrGekko** [comment]
Yep, I will need to cleanup the code a bit and when thats done i'l share the compiler (my cheesy name for a commandline tool :)) After that I would like to add functionality for people to add there custom translations or overwrite lines in the translations.

**Comment by HazemKhaled** [comment]
+5899 word translated in Turkish just now, i managed to import common keys from Magento 1 translation, i'll run same script on Arabic now

Thanks a lot

**Comment by MrGekko** [comment]
Wow! That is cool, [nice progress](https://github.com/Magento2Translations/language_tr_tr/commit/c894ad8587bd1cd4ff4269be26102502cb39691c), good work ! Some of the other languages (which are not that far along) could benefit from that script! Is it possible to share the script, or update some of the other crowdin languages?

**Comment by HazemKhaled** [comment]
Sure, i'll upload it soon on my account soon :)

**Comment by HazemKhaled** [comment]
Done https://github.com/HazemKhaled/Magento2i18nTools
